package com.jxnu.demo.bean;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table activity
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Activity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.mass_id
     *
     * @mbg.generated
     */
    private Integer massId;

    /**
     * Database Column Remarks:
     *   活动参加人数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.participants_number
     *
     * @mbg.generated
     */
    private Integer participantsNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.start_date
     *
     * @mbg.generated
     */
    private String startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.end_date
     *
     * @mbg.generated
     */
    private String endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.priority
     *
     * @mbg.generated
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.id
     *
     * @return the value of activity.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.id
     *
     * @param id the value for activity.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.mass_id
     *
     * @return the value of activity.mass_id
     *
     * @mbg.generated
     */
    public Integer getMassId() {
        return massId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.mass_id
     *
     * @param massId the value for activity.mass_id
     *
     * @mbg.generated
     */
    public void setMassId(Integer massId) {
        this.massId = massId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.participants_number
     *
     * @return the value of activity.participants_number
     *
     * @mbg.generated
     */
    public Integer getParticipantsNumber() {
        return participantsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.participants_number
     *
     * @param participantsNumber the value for activity.participants_number
     *
     * @mbg.generated
     */
    public void setParticipantsNumber(Integer participantsNumber) {
        this.participantsNumber = participantsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.start_date
     *
     * @return the value of activity.start_date
     *
     * @mbg.generated
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.start_date
     *
     * @param startDate the value for activity.start_date
     *
     * @mbg.generated
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.end_date
     *
     * @return the value of activity.end_date
     *
     * @mbg.generated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.end_date
     *
     * @param endDate the value for activity.end_date
     *
     * @mbg.generated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.content
     *
     * @return the value of activity.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.content
     *
     * @param content the value for activity.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.priority
     *
     * @return the value of activity.priority
     *
     * @mbg.generated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.priority
     *
     * @param priority the value for activity.priority
     *
     * @mbg.generated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.state
     *
     * @return the value of activity.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.state
     *
     * @param state the value for activity.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void cutDate(){
        if(this.startDate!=null){
            this.startDate=startDate.substring(0,10);
        }
        if(this.endDate!=null){
            this.endDate=endDate.substring(0,10);
        }
    }
}