package com.jxnu.demo.bean;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table contentUser
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Contentuser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contentUser.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contentUser.Administrator
     *
     * @mbg.generated
     */
    private String administrator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contentUser.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contentUser
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contentUser.id
     *
     * @return the value of contentUser.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contentUser.id
     *
     * @param id the value for contentUser.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contentUser.Administrator
     *
     * @return the value of contentUser.Administrator
     *
     * @mbg.generated
     */
    public String getAdministrator() {
        return administrator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contentUser.Administrator
     *
     * @param administrator the value for contentUser.Administrator
     *
     * @mbg.generated
     */
    public void setAdministrator(String administrator) {
        this.administrator = administrator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contentUser.password
     *
     * @return the value of contentUser.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contentUser.password
     *
     * @param password the value for contentUser.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }
}