package com.jxnu.demo.bean;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table mass_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class MassUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mass_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mass_user.mass_id
     *
     * @mbg.generated
     */
    private Integer massId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mass_user.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mass_user.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mass_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mass_user.id
     *
     * @return the value of mass_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mass_user.id
     *
     * @param id the value for mass_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mass_user.mass_id
     *
     * @return the value of mass_user.mass_id
     *
     * @mbg.generated
     */
    public Integer getMassId() {
        return massId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mass_user.mass_id
     *
     * @param massId the value for mass_user.mass_id
     *
     * @mbg.generated
     */
    public void setMassId(Integer massId) {
        this.massId = massId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mass_user.user_id
     *
     * @return the value of mass_user.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mass_user.user_id
     *
     * @param userId the value for mass_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mass_user.state
     *
     * @return the value of mass_user.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mass_user.state
     *
     * @param state the value for mass_user.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}