package com.jxnu.demo.bean;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table secondary_reply
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SecondaryReply implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secondary_reply.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secondary_reply.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secondary_reply.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secondary_reply.reply_id
     *
     * @mbg.generated
     */
    private Integer replyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secondary_reply.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secondary_reply.like_number
     *
     * @mbg.generated
     */
    private Integer likeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secondary_reply.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table secondary_reply
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secondary_reply.id
     *
     * @return the value of secondary_reply.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondary_reply.id
     *
     * @param id the value for secondary_reply.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secondary_reply.user_id
     *
     * @return the value of secondary_reply.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondary_reply.user_id
     *
     * @param userId the value for secondary_reply.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secondary_reply.content
     *
     * @return the value of secondary_reply.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondary_reply.content
     *
     * @param content the value for secondary_reply.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secondary_reply.reply_id
     *
     * @return the value of secondary_reply.reply_id
     *
     * @mbg.generated
     */
    public Integer getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondary_reply.reply_id
     *
     * @param replyId the value for secondary_reply.reply_id
     *
     * @mbg.generated
     */
    public void setReplyId(Integer replyId) {
        this.replyId = replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secondary_reply.date
     *
     * @return the value of secondary_reply.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondary_reply.date
     *
     * @param date the value for secondary_reply.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secondary_reply.like_number
     *
     * @return the value of secondary_reply.like_number
     *
     * @mbg.generated
     */
    public Integer getLikeNumber() {
        return likeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondary_reply.like_number
     *
     * @param likeNumber the value for secondary_reply.like_number
     *
     * @mbg.generated
     */
    public void setLikeNumber(Integer likeNumber) {
        this.likeNumber = likeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secondary_reply.state
     *
     * @return the value of secondary_reply.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondary_reply.state
     *
     * @param state the value for secondary_reply.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}