package com.jxnu.demo.dao;

import com.jxnu.demo.bean.Contentuser;
import com.jxnu.demo.bean.ContentuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contentUser
     *
     * @mbg.generated
     */
    long countByExample(ContentuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contentUser
     *
     * @mbg.generated
     */
    int deleteByExample(ContentuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contentUser
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contentUser
     *
     * @mbg.generated
     */
    int insert(Contentuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contentUser
     *
     * @mbg.generated
     */
    int insertSelective(Contentuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contentUser
     *
     * @mbg.generated
     */
    List<Contentuser> selectByExample(ContentuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contentUser
     *
     * @mbg.generated
     */
    Contentuser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contentUser
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Contentuser record, @Param("example") ContentuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contentUser
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Contentuser record, @Param("example") ContentuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contentUser
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Contentuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contentUser
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Contentuser record);

    Contentuser login(String Administrator);
}