package com.jxnu.demo.dao;

import com.jxnu.demo.bean.MassApply;
import com.jxnu.demo.bean.MassApplyExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface MassApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_apply
     *
     * @mbg.generated
     */
    long countByExample(MassApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_apply
     *
     * @mbg.generated
     */
    int deleteByExample(MassApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_apply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_apply
     *
     * @mbg.generated
     */
    int insert(MassApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_apply
     *
     * @mbg.generated
     */
    int insertSelective(MassApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_apply
     *
     * @mbg.generated
     */
    List<MassApply> selectByExample(MassApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_apply
     *
     * @mbg.generated
     */
    MassApply selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_apply
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MassApply record, @Param("example") MassApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_apply
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MassApply record, @Param("example") MassApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MassApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MassApply record);
    List<Map<String,String>> selectMassApply();
}