package com.jxnu.demo.dao;

import com.jxnu.demo.bean.MassInfo;
import com.jxnu.demo.bean.MassInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MassInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_info
     *
     * @mbg.generated
     */
    long countByExample(MassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_info
     *
     * @mbg.generated
     */
    int deleteByExample(MassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_info
     *
     * @mbg.generated
     */
    int insert(MassInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_info
     *
     * @mbg.generated
     */
    int insertSelective(MassInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_info
     *
     * @mbg.generated
     */
    List<MassInfo> selectByExample(MassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_info
     *
     * @mbg.generated
     */
    MassInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MassInfo record, @Param("example") MassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MassInfo record, @Param("example") MassInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MassInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MassInfo record);
}