package com.jxnu.demo.dao;

import com.jxnu.demo.bean.MassUser;
import com.jxnu.demo.bean.MassUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MassUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_user
     *
     * @mbg.generated
     */
    long countByExample(MassUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_user
     *
     * @mbg.generated
     */
    int deleteByExample(MassUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_user
     *
     * @mbg.generated
     */
    int insert(MassUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_user
     *
     * @mbg.generated
     */
    int insertSelective(MassUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_user
     *
     * @mbg.generated
     */
    List<MassUser> selectByExample(MassUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_user
     *
     * @mbg.generated
     */
    MassUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MassUser record, @Param("example") MassUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MassUser record, @Param("example") MassUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MassUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mass_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MassUser record);
}